# Generated by Django 6.0.1 on 2026-01-19 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Request Created'), ('ASSIGN', 'Assigned to Checker'), ('APPROVE', 'Approved'), ('REJECT', 'Rejected'), ('RESUBMIT', 'Resubmitted'), ('VIEW', 'Viewed')], help_text='Type of action', max_length=20)),
                ('remarks', models.TextField(blank=True, help_text='Additional remarks or comments')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Approval Log',
                'verbose_name_plural': 'Approval Logs',
                'db_table': 'admin_core_approval_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.RenameField(
            model_name='approvalrequest',
            old_name='action_type',
            new_name='request_type',
        ),
        migrations.RemoveField(
            model_name='approvalrequest',
            name='checker',
        ),
        migrations.RemoveField(
            model_name='approvalrequest',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='approvalrequest',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='approvalrequest',
            name='maker',
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='assigned_checker',
            field=models.ForeignKey(blank=True, help_text='CHECKER user assigned to review this request (must be from upper unit)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='checker_unit',
            field=models.ForeignKey(blank=True, help_text='Unit of the assigned checker (must be ancestor of maker_unit)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests_to_review', to='admin_core.unit'),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='created_by',
            field=models.ForeignKey(help_text='MAKER user who created this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the request'),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='maker_unit',
            field=models.ForeignKey(blank=True, help_text='Unit of the maker (for hierarchy-based routing)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests_made', to='admin_core.unit'),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='remarks',
            field=models.TextField(blank=True, help_text='Comments/remarks from the checker'),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when request was approved/rejected', null=True),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='CHECKER who reviewed this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='title',
            field=models.CharField(blank=True, help_text='Short title/subject of the request', max_length=200),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='payload',
            field=models.JSONField(blank=True, default=dict, help_text='JSON data containing request details'),
        ),
        migrations.AlterField(
            model_name='user',
            name='employee_id',
            field=models.CharField(help_text='Unique employee identifier (PF ID)', max_length=20, unique=True),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['status', 'assigned_checker'], name='admin_core__status_661592_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['created_by', 'status'], name='admin_core__created_940fb3_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['maker_unit', 'status'], name='admin_core__maker_u_8ed04b_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['checker_unit', 'status'], name='admin_core__checker_c8dd9a_idx'),
        ),
        migrations.AddField(
            model_name='approvallog',
            name='approval_request',
            field=models.ForeignKey(help_text='Associated approval request', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='admin_core.approvalrequest'),
        ),
        migrations.AddField(
            model_name='approvallog',
            name='performed_by',
            field=models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
