# Generated by Django 6.0.1 on 2026-01-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_core', '0002_approvallog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='unit_type',
            field=models.CharField(choices=[('CO', 'Corporate Office'), ('LHO', 'Local Head Office'), ('AO', 'Administrative Office'), ('RO', 'Regional Office'), ('BR', 'Branch')], help_text='Type of organizational unit', max_length=10),
        ),
    ]
